[tool.poetry]
name = "summit"
version = "0.3.0"
description = "Tools for optimizing chemical processes"
authors = ["Kobi Felton <kobi.c.f@gmail.com>"]
license = ""
readme = 'README.md'
repository = "https://github.com/sustainable-processes/summit"
homepage = "https://pypi.org/project/summit"
keywords = []

[tool.poetry.dependencies]
pandas = "1.0.3"
python = "^3.6.1"
GPy = "^1.9"
numpy = "1.18.0"
platypus-opt = "^1.0"
sklearn = "^0.0.0"
scipydirect = "^1.3"
pyrff = "^1.0.1"
SQSnobFit = "^0.4.3"
fastprogress = "^0.2.3"
tqdm = "^4.46.1"
ipywidgets = "^7.5.1"
matplotlib = "^3.2.2"
pymoo = "^0.4.1"
hiplot = "^0.1.16"
pathlib = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipdb = "^0.13.2"
jupyterlab = "^2.1.4"
black = "^19.10b0"
plotly = "^4.8.2"


[build-system]
requires = ["poetry>=0.12"]
build-backendpoet = "poetry.masonry.api"
