name: Run Tests
on: [push]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.8
        poetry_version: 1.0.10
        args: run python -m pytest --doctest-modules --ignore=case_studies --ignore=experiments
